version: '3'

services:
  db:
    image: mariadb:10.2.31
    container_name: easy-payments-db
    ports:
      - "${DATABASE_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'easy-payments'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
