server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki_easy_payments:3100/loki/api/v1/push

scrape_configs:
  - job_name: symfony
    static_configs:
      - targets:
        - localhost
        labels:
          job: symfony
          __path__: /var/log/symfony/*.log

  - job_name: nginx
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          __path__: /var/log/nginx/*.log